name: linting, testing, building
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
jobs:
  pipeline:
#    runs-on: ubuntu-latest
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
#      - name: build production project
#        run: npm run build:prod
#      - name: linting typescript
#        run: npm run eslint
#      - name: linting scss
#        run: npm run eslint:scss
#      - name: unit testing scss
#        run: npm run unitJest
      - name: build storybook
        run: npm run build-storybook
      - name: screenshot testing
        run: npm run test:ui:si